# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '12.x'
  displayName: 'Install Node.js'

- script: |
      npm install --if-present
      npm i -g serverless
      serverless package
      npm run build --if-present
  displayName: 'npm install and build'
  
- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(System.DefaultWorkingDirectory)/.serverless'
    ArtifactName: 'drop'
    publishLocation: 'Container'

- task: AzureRmWebAppDeployment@4
  inputs:
    ConnectionType: 'AzureRM'
    azureSubscription: 'MAIC - TEK Experts CR - v-juasol Group#2 (bddf3c59-769c-49a7-a515-6310ce264e6a)'
    appType: 'functionApp'
    WebAppName: 'jesumeServerlessNode'
    packageForLinux: '$(System.DefaultWorkingDirectory)/.serverless/*.zip'
